version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: restaurante_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurante

    ports:
      - "5433:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
